[project]
name = "lab-interop"
version = "0.1.0"
description = "Laboratorio simple de interoperabilidad con gRPC y eventos"
authors = [
    {name = "MarcoM3j14",email = "marcomejia2001@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "grpcio (>=1.74.0,<2.0.0)",
    "grpcio-tools (>=1.74.0,<2.0.0)",
    "protobuf (>=6.31.1,<7.0.0)",
    "pydantic (>=2.11.7,<3.0.0)",
    "redis (>=6.2.0,<7.0.0)"
]

[project.scripts]
grpc-server = "lab_interop.server:serve"
grpc-client = "lab_interop.client:main"
generate-stubs = "lab_interop.codegen:main"

[tool.poetry]
packages = [{include = "lab_interop", from = "src"}]

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 88
src_paths = ["src"]

[tool.ruff]
line-length = 88
target-version = "py312"
src = ["src"]

[tool.ruff.lint]
select = ["E", "F", "I"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "black (>=26.1.0,<27.0.0)",
    "isort (>=7.0.0,<8.0.0)",
    "ruff (>=0.14.13,<0.15.0)",
    "pre-commit (>=4.5.1,<5.0.0)"
]
