repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: ^Intermediate/Lab08/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^Intermediate/Lab08/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.12
    hooks:
      - id: ruff-check
        files: ^Intermediate/Lab08/
      - id: ruff-format
        files: ^Intermediate/Lab08/